name: mealique
description: "Mealique - Your app for meal planning and recipes."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  flutter_secure_storage: ^10.0.0
  flutter_slidable: ^4.0.3

  # Networking
  dio: ^5.5.0+1

  # Database (Drift & SQLite)
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.22
  path_provider: ^2.1.3
  path: ^1.9.0
  connectivity_plus: ^6.0.3
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  calendar_date_picker2: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # Code Generation fÃ¼r Drift
  build_runner: ^2.4.9
  drift_dev: ^2.18.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/mealique.png"
  web:
    generate: true
    image_path: "assets/mealique.png"
  windows:
    generate: true
    image_path: "assets/mealique.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/mealique.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/mealique.png
