name: mealique
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.8
  http: ^0.13.6
  flutter_secure_storage: ^8.0.0

  # Networking
  dio: ^5.4.0

  # Database (Drift & SQLite)
  drift: ^2.16.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.2
  path: ^1.9.0
  connectivity_plus: ^7.0.0
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

  # Code Generation fÃ¼r Drift
  build_runner: ^2.4.8
  drift_dev: ^2.16.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/mealique.png"
  web:
    generate: true
    image_path: "assets/mealique.png"
  windows:
    generate: true
    image_path: "assets/mealique.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/mealique.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/mealique.png